name: Build Ubuntu

on: [push]

jobs:
  ubuntu:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install deps
        run: sudo tools/debian-setup.sh --install-optional --install-deb-deps python3-pip -y
      - name: Mkdir
        run: mkdir build
      - name: Cmake
        working-directory: build
        run: cmake -GNinja ..
      - name: Build
        run: ninja
        working-directory: build
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Build debian pkg
        run: dpkg-buildpackage -b -us -uc -jauto
      - name: Move deb packages
        run: |
          mkdir deb
          mv ../*.deb deb
      - name: Upload deb packages
        uses: actions/upload-artifact@v1
        with:
          name: packages
          path: deb
